import 'package:flutter/material.dart';

class AppConfigServer extends ChangeNotifier {
  static final AppConfigServer _instance = AppConfigServer._internal();
  factory AppConfigServer() => _instance;
  AppConfigServer._internal();

  ThemeMode _themeMode = ThemeMode.light;
  Locale _locale = const Locale('en');

  ThemeMode get themeMode => _themeMode;
  Locale get locale => _locale;

  // Updated to local PC IP for physical device connectivity
  final String apiUrl = "http://10.110.80.87:8000";

  bool get isDarkMode => _themeMode == ThemeMode.dark;

  void toggleTheme() {
    _themeMode = _themeMode == ThemeMode.light ? ThemeMode.dark : ThemeMode.light;
    notifyListeners();
  }

  void setLocale(String langCode) {
    _locale = Locale(langCode);
    notifyListeners();
  }

  // Simple Localization Map
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'NutriScan',
      'profile': 'Profile',
      'home': 'Home',
      'stats': 'Stats',
      'settings': 'Settings',
      'sign_out': 'Sign Out',
      'language': 'Language',
      'appearance': 'Appearance',
      'personal_info': 'Personal Information',
      'notifications': 'Notifications',
      'privacy': 'Privacy & Security',
      'help': 'Help & Support',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'english': 'English',
      'hindi': 'Hindi',
      'account_settings': 'Account Settings',
      'consumed': 'Consumed',
      'balance': 'Balance',
      'todays_macros': "Today's Macros",
      'percentage_of_goal': '% of goal',
      'weekly_calories': 'Weekly Calories',
      'daily_intake': 'Daily intake',
      'target': 'Target',
      'weekly_insights': 'Weekly Insights',
      'high_intake_analysis': "High intake. You're fueling for intense activity!",
      'light_day_analysis': 'Light day. Good for active recovery.',
      'balanced_day_analysis': "Balanced day. You're maintaining goal stability.",
      'weekend_caution': 'Weekend Caution',
      'weekday_progress': 'Weekday Progress',
      'weekend_tip': 'Calories usually peak on weekends. Try walking 2k more steps.',
      'consistent_routine': 'Consistent routine detected. Keep following your meal plan.',
      'macro_balance': 'Macro Balance',
      'protein_optimal': 'Your protein intake was optimal for muscle recovery today.',
      'aura_point_tip': 'Aura Point Tip',
      'cheat_meal_tip': 'Plan a cheat meal wisely for tomorrow.',
      'early_dinner_tip': 'Early dinner suggested for better sleep quality.',
      'analysis_suffix': 'Analysis',
      'nutriscan_ai_secure': 'NUTRISCAN AI SECURE ANALYSIS',
      'detected_today': 'Detected Today',
      'confidence': 'Confidence',
      'enhanced': 'ENHANCED',
      'real_time': 'REAL-TIME',
      'analytics_tab': 'Analytics',
      'components_tab': 'Components',
      'kcal_unit': 'KCAL',
      'advisory_text': "This meal provides 45g of protein, covering 35% of your daily need. Excellent for the 'Build Muscle' phase.",
      'profile_updated': 'Profile image updated locally!',
      'update_failed': 'Failed to pick image:',
      'name_label': 'Name',
      'email_label': 'Email',
      'status_label': 'Status',
      'premium_member': 'Premium Member',
      'notification_updated': 'Notification settings updated',
      'need_help': 'Need help? Contact support at support@nutriscan.ai',
      'ai_learning_text': 'Our AI model is continuously learning to provide better nutritional insights.',
      'app_settings': 'App Settings',
      'precision_nutrition_ai': 'Precision Nutrition AI',
      'or': 'OR',
      'error_invalid_credentials': 'Invalid email or password',
      'error_google_signin': 'Google sign-in failed',
      'enter_your': 'Enter your',
      'create_account_title': 'CREATE\nACCOUNT',
      'tagline_journey': 'Start your precision nutrition journey',
      'confirm_password': 'Confirm Password',
      'error_email_in_use': 'Email already in use or invalid',
      'already_have_account': 'Already have an account?',
      'required': 'Required',
      'min_6_chars': 'Min 6 chars',
      'spectrum': 'SPECTRUM',
      'privacy_title': 'Privacy & Security',
      'privacy_desc': 'Your data is encrypted and stored securely. We do not share your health data with third parties without your explicit consent.',
      'security_level': 'Security Level',
      'high': 'Strong',
      'close': 'Close',
      'select_language': 'Select Language',
      'weight_loss': 'Weight Loss',
      'weight_gain': 'Weight Gain',
      'muscle_build': 'Muscle Build',
      'manage_diabetes': 'Manage Diabetes',
      'current_plan': 'Current Plan',
      'protein': 'Protein',
      'carbs': 'Carbs',
      'fats': 'Fats',
      'burned': 'Burned',
      'steps': 'Steps',
      'active_min': 'Active min',
      'kcal_per_day': 'kcal/day',
      'save_goals': 'Save Goals',
      'sync_workouts': 'Sync workouts and activity data to adjust your calorie budget',
      'your_goal': 'Your Goal',
      'goal_desc': 'Choose what you want to achieve',
      'daily_target': 'Daily Calorie Target',
      'macro_distribution': 'Macro Distribution',
      'macro_desc': 'Adjust your macro percentages',
      'fitness_sync': 'Fitness Sync',
      'today_activity': "Today's Activity",
      'recent_workouts': 'Recent Workouts',
      'barcode_analysis': 'Barcode Analysis (Coming Soon)',
      'progress_title': "Today's Progress",
      'kcal_remaining': 'kcal remaining',
      'meals_logged': 'meals logged',
      'scan_meal': 'Scan Your Meal',
      'scan_desc': 'Take a photo and get instant analysis',
      'todays_meals': "Today's Meals",
      'breakfast': 'Breakfast',
      'lunch': 'Lunch',
      'dinner': 'Dinner',
      'moderate': 'Moderate',
      'refine_analysis': 'Refine Analysis',
      'refining_accuracy': 'Refining accuracy',
      'how_prepared': 'How was the meal prepared?',
      'restaurant_mode': 'Restaurant mode',
      'home_cooked': 'Home-cooked (Healthy)',
      'light_prep': 'Light preparation',
      'portion_size': 'What was the approximate portion size?',
      'small_bowl': 'Small Bowl',
      'medium_bowl': 'Medium Bowl',
      'large_dish': 'Large Dish',
      'skip_question': 'Skip this question',
      'total_nutrition': 'Total Nutrition',
      'ai_analyzed': 'AI Analyzed',
      'analyzing_meal': 'Analyzing Your Meal',
      'ai_thinking': 'Our AI is thinking... identifying foods, portions, and calculating precise nutrition data',
      'id_ingredients': 'Identifying ingredients',
      'analyzing_portions': 'Analyzing portions',
      'predicting_impact': 'Predicting nutritional impact',
      'gi_index': 'GI Index',
      'low_impact': 'Low Impact',
      'satiety': 'Satiety',
      'health_score': 'Health Score',
      'advisory': 'ADVISORY',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'create_account': 'Create Account',
      'email_address': 'Email Address',
      'password': 'Password',
      'google_continue': 'Continue with Google',
      'new_to_spectrum': 'New to Spectrum?',
      'maintain_weight': 'Maintain Weight',
      'calorie_deficit': 'Calorie deficit for sustainable weight loss',
      'high_protein': 'High protein for muscle growth',
      'balanced_nutrition_lifestyle': 'Balanced nutrition for your lifestyle',
      'low_carb_balanced': 'Low carb, balanced nutrition',
      'per_day': 'per day',
      'connected': 'Connected',
      'not_connected': 'Not connected',
      'disconnect': 'Disconnect',
      'connect': 'Connect',
      'auto_sync': 'Auto-sync',
      'synced': 'Synced',
      'calorie_budget_adjusted': 'Calorie Budget Adjusted',
      'based_on_burned': 'Based on your 487 kcal burned today, you can eat an additional ',
      'meet_goals': 'and still meet your goals.',
      'ai_powered_analysis': 'AI-Powered Food Analysis',
      'morning_run': 'Morning Run',
      'strength_training': 'Strength Training',
      'edge_processing': 'Edge Processing',
      'edge_processing_desc': 'We use Instance Segmentation to isolate food and discard background pixels (faces/interiors) before transmission. This protects your privacy while automatically scrubbing sensitive GPS metadata.',
      'secure_integration': 'Secure Integration',
      'secure_integration_desc': 'OAuth 2.0 ensures encrypted syncing with Google Fit/Apple Health without accessing your credentials. Use the "Privacy Dashboard" to toggle exactly which health metrics the AI can see.',
      'transparent_governance': 'Transparent Governance',
      'transparent_governance_desc': 'Aligned with GDPR/DPDP, our "Right to Forget" enables one-tap permanent history deletion. We maintain a strict "Zero-Sale" policy; your data is never monetized or shared with third parties.',
      'bank_grade_encryption': 'Bank-Grade Encryption',
      'bank_grade_encryption_desc': 'All data is secured with AES-256 encryption at rest and in transit. Federated Feedback improves our AI using anonymized mathematical updates instead of your original private images.',
      'safety_guardrails': 'Safety Guardrails',
      'safety_guardrails_desc': 'Uncertainty-Aware Bands flag ambiguous ingredients to avoid false precision. All results include medical disclaimers, clarifying that AI insights are approximations, not professional medical advice.',
      'daily_tip': 'Daily Tip',
      'tip_1': 'Drink at least 3L of water today for better metabolism.',
      'tip_2': 'Include protein in every meal to maintain muscle mass.',
      'tip_3': 'Sleep for 7-8 hours to improve recovery and focus.',
    },
    'hi': {
      'app_name': 'न्यूट्रीस्कैन',
      'profile': 'प्रोफ़ाइल',
      'home': 'होम',
      'stats': 'आँकड़े',
      'settings': 'सेटिंग्स',
      'sign_out': 'साइन आउट',
      'language': 'भाषा',
      'appearance': 'दिखावट',
      'personal_info': 'व्यक्तिगत जानकारी',
      'notifications': 'सूचनाएं',
      'privacy': 'गोपनीयता और सुरक्षा',
      'help': 'सहायता और समर्थन',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'account_settings': 'खाता सेटिंग',
      'consumed': 'उपभोग किया',
      'balance': 'शेष',
      'todays_macros': "आज के मैक्रोज़",
      'percentage_of_goal': 'लक्ष्य का %',
      'weekly_calories': 'साप्ताहिक कैलोरी',
      'daily_intake': 'दैनिक सेवन',
      'target': 'लक्ष्य',
      'weekly_insights': 'साप्ताहिक अंतर्दृष्टि',
      'high_intake_analysis': "उच्च सेवन। आप तीव्र गतिविधि के लिए ईंधन भर रहे हैं!",
      'light_day_analysis': 'हल्का दिन। सक्रिय रिकवरी के लिए अच्छा है।',
      'balanced_day_analysis': "संतुलित दिन। आप लक्ष्य स्थिरता बनाए हुए हैं।",
      'weekend_caution': 'सप्ताहांत सावधानी',
      'weekday_progress': 'सप्ताह के दिन की प्रगति',
      'weekend_tip': 'आमतौर पर सप्ताहांत पर कैलोरी चरम पर होती है। 2k और कदम चलने की कोशिश करें।',
      'consistent_routine': 'लगातार दिनचर्या का पता चला। अपनी भोजन योजना का पालन करते रहें।',
      'macro_balance': 'मैक्रो संतुलन',
      'protein_optimal': 'मांसपेशियों की रिकवरी के लिए आज आपका प्रोटीन सेवन इष्टतम था।',
      'aura_point_tip': 'आभा बिंदु टिप',
      'cheat_meal_tip': 'कल के लिए सोच-समझकर चीट मील की योजना बनाएं।',
      'early_dinner_tip': 'बेहतर नींद की गुणवत्ता के लिए जल्दी रात के खाने का सुझाव दिया जाता है।',
      'analysis_suffix': 'विश्लेषण',
      'nutriscan_ai_secure': 'न्यूट्रीस्कैन एआई सुरक्षित विश्लेषण',
      'detected_today': 'आज पता चला',
      'confidence': 'विश्वास',
      'enhanced': 'उन्नत',
      'real_time': 'वास्तविक समय',
      'analytics_tab': 'विश्लेषण',
      'components_tab': 'अवयव',
      'kcal_unit': 'किलो कैलोरी',
      'advisory_text': "यह भोजन 45g प्रोटीन प्रदान करता है, जो आपकी दैनिक आवश्यकता का 35% कवर करता है। 'मांसपेशियों का निर्माण' चरण के लिए उत्कृष्ट।",
      'profile_updated': 'प्रोफ़ाइल छवि स्थानीय रूप से अपडेट की गई!',
      'update_failed': 'छवि चुनने में विफल:',
      'name_label': 'नाम',
      'email_label': 'ईमेल',
      'status_label': 'स्थिति',
      'premium_member': 'प्रीमियम सदस्य',
      'notification_updated': 'सुचना सेटिंग्स अपडेट की गईं',
      'need_help': 'मदद चाहिए? support@nutriscan.ai पर सहायता से संपर्क करें',
      'ai_learning_text': 'हमारा एआई मॉडल बेहतर पोषण संबंधी अंतर्दृष्टि प्रदान करने के लिए लगातार सीख रहा है।',
      'app_settings': 'ऐप सेटिंग',
      'precision_nutrition_ai': 'प्रेसिजन न्यूट्रिशन एआई',
      'or': 'या',
      'error_invalid_credentials': 'अमान्य ईमेल या पासवर्ड',
      'error_google_signin': 'Google साइन-इन विफल',
      'enter_your': 'अपना दर्ज करें',
      'create_account_title': 'खाता\nबनाएं',
      'tagline_journey': 'अपनी सटीक पोषण यात्रा शुरू करें',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'error_email_in_use': 'ईमेल पहले से उपयोग में है या अमान्य है',
      'already_have_account': 'क्या आपके पास पहले से एक खाता है?',
      'required': 'आवश्यक',
      'min_6_chars': 'न्यूनतम 6 अक्षर',
      'spectrum': 'स्पेक्ट्रम',
      'privacy_title': 'गोपनीयता और सुरक्षा',
      'privacy_desc': 'आपका डेटा एन्क्रिप्टेड और सुरक्षित रूप से संग्रहीत है। हम आपकी स्पष्ट सहमति के बिना तीसरे पक्ष के साथ आपका स्वास्थ्य डेटा साझा नहीं करते हैं।',
      'security_level': 'सुरक्षा स्तर',
      'high': 'मजबूत',
      'close': 'बंद करें',
      'select_language': 'भाषा चुनें',
      'weight_loss': 'वजन घटाना',
      'weight_gain': 'वजन बढ़ना',
      'muscle_build': 'मांसपेशियों का निर्माण',
      'manage_diabetes': 'मधुमेह प्रबंधन',
      'current_plan': 'वर्तमान योजना',
      'protein': 'प्रोटीन',
      'carbs': 'कार्ब्स',
      'fats': 'वसा',
      'burned': 'बर्न किया',
      'steps': 'कदम',
      'active_min': 'सक्रिय मिनट',
      'kcal_per_day': 'किलो कैलोरी/दिन',
      'save_goals': 'लक्ष्य सहेजें',
      'sync_workouts': 'अपने कैलोरी बजट को समायोजित करने के लिए वर्कआउट और गतिविधि डेटा सिंक करें',
      'your_goal': 'आपका लक्ष्य',
      'goal_desc': 'चुनें कि आप क्या हासिल करना चाहते हैं',
      'daily_target': 'दैनिक कैलोरी लक्ष्य',
      'macro_distribution': 'मैक्रो वितरण',
      'macro_desc': 'अपने मैक्रो प्रतिशत को समायोजित करें',
      'fitness_sync': 'फिटनेस सिंक',
      'today_activity': "आज की गतिविधि",
      'recent_workouts': 'हाल के वर्कआउट',
      'daily_tip': 'दैनिक टिप',
      'tip_1': 'बेहतर चयापचय के लिए आज कम से कम 3L पानी पिएं।',
      'tip_2': 'मांसपेशियों को बनाए रखने के लिए हर भोजन में प्रोटीन शामिल करें।',
      'tip_3': 'रिकवरी और फोकस में सुधार के लिए 7-8 घंटे सोएं।',
      'edge_processing': 'एज प्रोसेसिंग',
      'edge_processing_desc': 'हम संचरण से पहले भोजन को अलग करने और पृष्ठभूमि पिक्सेल (चेहरे/अंदरूनी भाग) को त्यागने के लिए इंस्टेंस सेगमेंटेशन का उपयोग करते हैं। यह संवेदनशील GPS मेटाडेटा को स्वचालित रूप से साफ़ करते हुए आपकी गोपनीयता की रक्षा करता है।',
      'secure_integration': 'सुरक्षित एकीकरण',
      'secure_integration_desc': 'OAuth 2.0 आपके क्रेडेंशियल्स तक पहुँचे बिना Google Fit/Apple Health के साथ एन्क्रिप्टेड सिंकिंग सुनिश्चित करता है। "गोपनीयता डैशबोर्ड" का उपयोग करें और ठीक से टॉगल करें कि AI कौन से स्वास्थ्य मेट्रिक्स देख सकता है।',
      'transparent_governance': 'पारदर्शी शासन',
      'transparent_governance_desc': 'GDPR/DPDP के साथ संरेखित, हमारा "भूलने का अधिकार" एक-टैप स्थायी इतिहास विलोपन को सक्षम बनाता है। हम एक सख्त "शून्य-बिक्री" नीति बनाए रखते हैं; आपका डेटा कभी भी मुद्रीकृत या तीसरे पक्ष के साथ साझा नहीं किया जाता है।',
      'bank_grade_encryption': 'बैंक-ग्रेड एन्क्रिप्शन',
      'bank_grade_encryption_desc': 'सभी डेटा को आराम और पारगमन में AES-256 एन्क्रिप्शन के साथ सुरक्षित किया गया है। फ़ेडरेटेड फ़ीडबैक आपकी मूल निजी छवियों के बजाय अनाम गणितीय अपडेट का उपयोग करके हमारे AI में सुधार करता है।',
      'safety_guardrails': 'सुरक्षा सुरक्षा उपाय',
      'safety_guardrails_desc': 'अनिश्चितता-जागरूक बैंड झूठी सटीकता से बचने के लिए अस्पष्ट सामग्री को चिह्नित करते हैं। सभी परिणामों में चिकित्सा अस्वीकरण शामिल हैं, जो स्पष्ट करते हैं कि AI अंतर्दृष्टि अनुमान हैं, पेशेवर चिकित्सा सलाह नहीं।',
      'barcode_analysis': 'बारकोड विश्लेषण (जल्द आ रहा है)',
      'progress_title': 'आज की प्रगति',
      'kcal_remaining': 'किलो कैलोरी शेष',
      'meals_logged': 'भोजन लॉग किया गया',
      'scan_meal': 'अपना भोजन स्कैन करें',
      'scan_desc': 'एक फोटो लें और तुरंत विश्लेषण प्राप्त करें',
      'todays_meals': 'आज का भोजन',
      'breakfast': 'नाश्ता',
      'lunch': 'दोपहर का भोजन',
      'dinner': 'रात का खाना',
      'moderate': 'मध्यम',
      'refine_analysis': 'विश्लेषण में सुधार करें',
      'refining_accuracy': 'सटीकता में सुधार',
      'how_prepared': 'भोजन कैसे तैयार किया गया था?',
      'restaurant_mode': 'रेस्टोरेंट मोड',
      'home_cooked': 'घर का बना (स्वस्थ)',
      'light_prep': 'हल्की तैयारी',
      'portion_size': 'भोजन का अनुमानित आकार क्या था?',
      'small_bowl': 'छोटा कटोरा',
      'medium_bowl': 'मध्यम कटोरा',
      'large_dish': 'बड़ी डिश',
      'skip_question': 'इस प्रश्न को छोड़ें',
      'total_nutrition': 'कुल पोषण',
      'ai_analyzed': 'एआई विश्लेषण',
      'analyzing_meal': 'भोजन का विश्लेषण कर रहे हैं',
      'ai_thinking': 'हमारा एआई सोच रहा है... भोजन, मात्रा की पहचान कर रहा है और सटीक पोषण डेटा की गणना कर रहा है',
      'id_ingredients': 'सामग्री की पहचान',
      'analyzing_portions': 'मात्रा का विश्लेषण',
      'predicting_impact': 'पोषण संबंधी प्रभाव का पूर्वानुमान',
      'gi_index': 'जीआई इंडेक्स',
      'low_impact': 'कम प्रभाव',
      'satiety': 'तृप्ति',
      'health_score': 'स्वास्थ्य स्कोर',
      'advisory': 'सलाह',
      'sign_in': 'साइन इन करें',
      'sign_up': 'साइन अप करें',
      'create_account': 'खाता बनाएं',
      'email_address': 'ईमेल पता',
      'password': 'पासवर्ड',
      'google_continue': 'गूगल के साथ जारी रखें',
      'new_to_spectrum': 'न्यूट्रीस्कैन में नए हैं?',
      'maintain_weight': 'वजन बनाए रखें',
      'calorie_deficit': 'स्थायी वजन घटाने के लिए कैलोरी की कमी',
      'high_protein': 'मांसपेशियों की वृद्धि के लिए उच्च प्रोटीन',
      'balanced_nutrition_lifestyle': 'आपकी जीवनशैली के लिए संतुलित पोषण',
      'low_carb_balanced': 'कम कार्ब, संतुलित पोषण',
      'per_day': 'प्रति दिन',
      'connected': 'जुड़ा हुआ',
      'not_connected': 'जुड़ा नहीं है',
      'disconnect': 'डिस्कनेक्ट करें',
      'connect': 'कनेक्ट करें',
      'auto_sync': 'ऑटो सिंक',
      'synced': 'सिंक किया गया',
      'calorie_budget_adjusted': 'कैलोरी बजट समायोजित',
      'based_on_burned': 'आज आपके 487 किलो कैलोरी बर्न होने के आधार पर, आप अतिरिक्त खा सकते हैं ',
      'meet_goals': 'और फिर भी अपने लक्ष्यों को पूरा करें।',
      'ai_powered_analysis': 'एआई-पावर्ड फूड एनालिसिस',
      'morning_run': 'सुबह की दौड़',
      'strength_training': 'शक्ति प्रशिक्षण',
    },
  };

  String translate(String key) {
    return _localizedValues[_locale.languageCode]?[key] ?? key;
  }
}
